DROP TABLE IF EXISTS PATIENTS CASCADE;

CREATE TABLE PATIENTS (
    ROW_ID          INT,
    SUBJECT_ID      INT PRIMARY KEY,
    GENDER          VARCHAR(5),
    DOB             TIMESTAMP,
    DOD             TIMESTAMP,
    DOD_HOSP        TIMESTAMP,
    DOD_SSN         TIMESTAMP,
    EXPIRE_FLAG     INT
);

DROP TABLE IF EXISTS ADMISSIONS CASCADE;

CREATE TABLE ADMISSIONS (
    ROW_ID               INT PRIMARY KEY,
    SUBJECT_ID           INT REFERENCES PATIENTS(SUBJECT_ID),
    HADM_ID              INT UNIQUE,
    ADMITTIME            TIMESTAMP,
    DISCHTIME            TIMESTAMP,
    DEATHTIME            TIMESTAMP,
    ADMISSION_TYPE       VARCHAR(50),
    ADMISSION_LOCATION   VARCHAR(100),
    DISCHARGE_LOCATION   VARCHAR(100),
    INSURANCE            VARCHAR(50),
    LANGUAGE             VARCHAR(10),
    RELIGION             VARCHAR(50),
    MARITAL_STATUS       VARCHAR(50),
    ETHNICITY            VARCHAR(100),
    EDREGTIME            TIMESTAMP,
    EDOUTTIME            TIMESTAMP,
    DIAGNOSIS            VARCHAR(255),
    HOSPITAL_EXPIRE_FLAG INT,
    HAS_CHARTEVENTS_DATA INT
);

DROP TABLE IF EXISTS ICUSTAYS CASCADE;

CREATE TABLE ICUSTAYS (
    ROW_ID          INT PRIMARY KEY,
    SUBJECT_ID      INT REFERENCES PATIENTS(SUBJECT_ID),
    HADM_ID         INT REFERENCES ADMISSIONS(HADM_ID),
    ICUSTAY_ID      INT UNIQUE,
    DBSOURCE        VARCHAR(20),
    FIRST_CAREUNIT  VARCHAR(20),
    LAST_CAREUNIT   VARCHAR(20),
    FIRST_WARDID    INT,
    LAST_WARDID     INT,
    INTIME          TIMESTAMP,
    OUTTIME         TIMESTAMP,
    LOS             NUMERIC
);

DROP TABLE IF EXISTS NOTEEVENTS CASCADE;

CREATE TABLE NOTEEVENTS (
    ROW_ID        INT PRIMARY KEY,
    SUBJECT_ID    INT REFERENCES PATIENTS(SUBJECT_ID),
    HADM_ID       INT REFERENCES ADMISSIONS(HADM_ID),
    CHARTDATE     DATE,
    CATEGORY      VARCHAR(50),
    DESCRIPTION   VARCHAR(255),
    CGID          INT,
    ISERROR       VARCHAR(10),
    TEXT          TEXT
);

DROP TABLE IF EXISTS D_ICD_DIAGNOSES CASCADE;

CREATE TABLE D_ICD_DIAGNOSES (
    ROW_ID      INT PRIMARY KEY,
    ICD9_CODE   VARCHAR(10) UNIQUE,
    SHORT_TITLE VARCHAR(255),
    LONG_TITLE  VARCHAR(255)
);

DROP TABLE IF EXISTS DIAGNOSES_ICD CASCADE;

CREATE TABLE DIAGNOSES_ICD (
    ROW_ID      INT PRIMARY KEY,
    SUBJECT_ID  INT REFERENCES PATIENTS(SUBJECT_ID),
    HADM_ID     INT REFERENCES ADMISSIONS(HADM_ID),
    SEQ_NUM     INT,
    ICD9_CODE   VARCHAR(10) REFERENCES D_ICD_DIAGNOSES(ICD9_CODE)
);
